import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { spacing } from '../../../theme/spacing';
import { borderRadius } from '../../../theme/radii';

const sem = colors.semantic;

/** Issue #100-12 (#436): レシート詳細コンポーネントの固有スタイル */
export const receiptDetailStyles = StyleSheet.create({
  detailScroll: { flex: 1 },
  placeholderContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  emptyText: { color: colors.text.muted },
  wideContentWrapper: { flexDirection: 'row', padding: 30, width: '100%', alignItems: 'flex-start' },
  mobileContentWrapper: { flexDirection: 'column', padding: spacing.lg },
  wideImageColumn: { width: 400, marginRight: 40 },
  wideInfoColumn: { flex: 1 },
  mobileImageArea: { width: '100%', marginBottom: 25 },
  mobileInfoArea: { width: '100%' },
  imageWrapper: {
    width: '100%',
    height: 600,
    backgroundColor: colors.surface,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  mobileImageWrapper: { height: 350 },
  noImagePlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.surface },
  receiptImage: { width: '100%', height: '100%' },
  detailHeaderInner: { marginBottom: spacing.lg },
  detailTitle: { fontSize: 24, fontWeight: 'bold', color: colors.text.main },
  titleInput: { marginBottom: spacing.xs },
  titleInputText: { fontSize: 24, fontWeight: 'bold' },
  detailDate: { fontSize: 16, color: colors.text.muted, marginTop: spacing.xs },
  dateInput: { marginTop: spacing.xs },
  detailTotalContainer: {
    alignItems: 'flex-end',
    marginBottom: 30,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  detailTotalLabel: { fontSize: 13, color: colors.text.muted },
  detailTotalValue: { fontSize: 38, fontWeight: 'bold', color: colors.text.main },
  itemsSection: { marginBottom: spacing.lg },
  itemsSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.secondary,
    marginBottom: spacing.md,
    textTransform: 'uppercase',
  },
  detailItemRow: {
    flexDirection: 'column',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: sem.table.rowBorder,
  },
  detailItemTop: { marginBottom: 10 },
  detailItemName: { fontSize: 17, fontWeight: '600', color: colors.text.main, marginBottom: spacing.xs },
  itemNameInput: { marginBottom: spacing.xs },
  detailPriceContainer: { flexDirection: 'row', alignItems: 'baseline' },
  detailItemPrice: { fontWeight: '700', color: colors.primary, fontSize: 16 },
  detailItemSub: { fontSize: 12, color: colors.text.muted, marginLeft: 6 },
  detailItemBottom: { width: '100%' },
  editControls: { flexDirection: 'row', justifyContent: 'flex-end', marginBottom: 10, gap: 10 },
  splitButtonOverride: { backgroundColor: sem.info.bg, borderColor: sem.info.border },
  editPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  priceInput: { width: 100, minHeight: 40 },
  quantityInput: { width: 72, minHeight: 40 },
  currencySymbol: { fontSize: 14, color: colors.text.muted },
  multiplier: { fontSize: 14, color: colors.text.muted },
  categorySelect: { marginTop: spacing.xs },
  taxSection: {
    marginTop: spacing.lg,
    paddingVertical: 15,
    borderTopWidth: 2,
    borderTopColor: sem.divider,
    borderStyle: 'dashed',
  },
  taxRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  taxLabel: { fontSize: 14, color: colors.text.muted, fontWeight: '600' },
  taxValue: { fontSize: 16, color: colors.text.main, fontWeight: '700' },
  editTaxRow: { flexDirection: 'row', alignItems: 'center' },
  taxInput: { width: 120, minHeight: 40 },
  scrollFooter: { height: 50 },
});
